### ISSUE TITLE
Can only remove recursive type definitions on union types not "TypeReference"

### ISSUE THREAD

**Issue by fefrei** [metadevpro/ts-pegjs#119]
Starting with version 4.0.0, `ts-pegjs` fails to handle recursive rules like this:

    start = "(" e: start ")" { return e; }

Peggy itself has no issue with this, but `ts-pegjs` struggles computing the types:

```
Error: Can only remove recursive type definitions on union types not "TypeReference"
    at getInfoFromDiagnostic (C:\Users\felix\git\pseuco-ccs-interpreter\node_modules\ts-pegjs\dist\tspegjs.js:339:11)
    at C:\Users\felix\git\pseuco-ccs-interpreter\node_modules\ts-pegjs\dist\tspegjs.js:304:41
    at Array.map (<anonymous>)
    at pruneCircularReferences (C:\Users\felix\git\pseuco-ccs-interpreter\node_modules\ts-pegjs\dist\tspegjs.js:304:30)
    at TypeExtractor.getTypes (C:\Users\felix\git\pseuco-ccs-interpreter\node_modules\ts-pegjs\dist\tspegjs.js:482:5)
    at generateParser (C:\Users\felix\git\pseuco-ccs-interpreter\node_modules\ts-pegjs\dist\tspegjs.js:779:35)
    at C:\Users\felix\git\pseuco-ccs-interpreter\node_modules\peggy\lib\compiler\index.js:119:9
    at Array.forEach (<anonymous>)
    at C:\Users\felix\git\pseuco-ccs-interpreter\node_modules\peggy\lib\compiler\index.js:116:21
    at Array.forEach (<anonymous>)
```

Version 3.1.0 could still handle this.

**Comment by iccicci** [comment]
+1

**Comment by pjmolina** [comment]
> Sorry @pjmolina , are you still supporting this package?

Yes! We still need to review the latest changes in Peggy. We accept insights, and PR ;-)

**Comment by iccicci** [comment]
Thank you for you quick and kind answer!

Unfortunately I'm not able to do none of them 😞 I trust on you.

**Comment by iccicci** [comment]
Hint!

I have two rules called `set` and `map`.
Renaming them to `set2` and `map2` this error disapperaed.

**Comment by iccicci** [comment]
Simply commenting out the check in my `node_modules` directoy, everithing seems to work fine...
I can't understand neither the meaning of `getInfoFromDiagnostic` function nor its last check (the one I tried to comment out)... which is the meaning of the check?

```
  if (!typeBodyNode.isKind(ts.SyntaxKind.UnionType)) {
    throw new Error(
      `Can only remove recursive type definitions on union types not "${typeBodyNode.getKindName()}"`
    );
  }
```

**Comment by iccicci** [comment]
As a quick workaround: adding `skipTypeComputation: true` to `tspegjs` in `options` to `peggy.generate` call, makes the check throwing this error to be skipped and the error not being thrown.
