### ISSUE TITLE
Cannot assign to 'peg$startRuleIndex' because it is a constant or a read-only property.

### ISSUE THREAD

**Issue by StoneCypher** [metadevpro/ts-pegjs#12]
```
src/ts/fslp.js → build/fslp.js...
[!] (rpt2 plugin) Error: C:/Users/john/projects/fslp/build/gen/parser.ts(189,5): semantic error TS2540 Cannot assign to 'peg$startRuleIndex' because it is a constant or a read-only property.
build\gen\parser.ts
Error: C:/Users/john/projects/fslp/build/gen/parser.ts(189,5): semantic error TS2540 Cannot assign to 'peg$startRuleIndex' because it is a constant or a read-only property.
    at error (C:\Users\john\projects\fslp\node_modules\rollup\dist\rollup.js:170:15)
    at C:\Users\john\projects\fslp\node_modules\rollup\dist\rollup.js:17413:17
    at <anonymous>
```

**Comment by StoneCypher** [comment]
Can be triggered with this peg:

```

_LineTerminator
  = [\n\r\u2028\u2029]

_BlockCommentTail
  = "*/"
  / . _BlockCommentTail

_BlockComment "block comment"
  = "/*" _BlockCommentTail

_EOF
  = !.

_LineCommentTail
  = _LineTerminator
  / _EOF
  / . _LineCommentTail

_LineComment "line comment"
  = "//" _LineCommentTail

_WS "whitespace"
  = _BlockComment _WS? { return { term: 'whitespace', value: undefined, location: location() }; }
  / _LineComment  _WS? { return { term: 'whitespace', value: undefined, location: location() }; }
  / [ \t\r\n\v]+  _WS? { return { term: 'whitespace', value: undefined, location: location() }; }
```

**Comment by pjmolina** [comment]
Is this still an issue?
I will find the time to reproduce it and investigate if so.

**Comment by pjmolina** [comment]
No able to reproduce it @StoneCypher 
Closing it.
Feel free to open again with a repro-sample.

**Comment by StoneCypher** [comment]
sorry, didn't see the previous outcall

i went and tried to repro and cannot.  this may have been a transient system issue of some kind.  apologies

i will try to make better reports in the future.  this should have been prevented

**Comment by pjmolina** [comment]
👍 No problem!
